### ISSUE TITLE
global `axios.interceptors` is vulnerable

### ISSUE THREAD

**Issue by Skn0tt** [digitalservicebund/useid-eservice-sdk#3]
Hi there! I'm a big fan of what the Digital Service is doing, and was browsing through the code out of interest.

In https://github.com/digitalservicebund/useid-eservice-sdk/blob/7e8906df61e9499720889e0045b34162908b9e27/src/UseIdAPI.ts#L11, and I think in some other places as well, you're using `axios.interceptors.request.use` from the global `axios` import. This injects your API Key into the global axios namespace, and it'll also be added onto other axios requests. This includes requests that are made inside other packages that also use `axios`, and could result in API Keys being sent to endpoints that it shouldn't be sent to. It also breaks if a package consuming the SDK is also using the global interceptors.

To fix it, I'd recommend to use an [Axios Instances](https://axios-http.com/docs/instance). It achieves exactly what you're looking for, and doesn't suffer from the same global-namespace problem.

**Comment by mpanne** [comment]
Hi @Skn0tt, thank you for your interest in the project and for pointing out this issue. We will look into it and take care!
Feel free to create a PR, though, if you feel the urge. 😉

**Comment by Skn0tt** [comment]
Absolutely! Opened #4 :)
